### PR TITLE
Changing 'pluginId' to 'xmlId' when publishing the plugin

### LINKED ISSUE #78: Unable to upload the plugin to marketplace - uses incorrect Id
I tried using `sbt uploadPlugin` to publish [my plugin](https://plugins.jetbrains.com/plugin/13820-zio-for-intellij) to the marketplace, however it failed with:

```
Error:  Failed to upload plugin
Error:  (400) : For input string: "zio.intellij.zio-intellij"
```

Upon deeper inspection, and reading the documentation for the [`uploadPlugin` API](https://plugins.jetbrains.com/docs/marketplace/plugin-upload.html), it seems that the sbt-idea-plugin extracts the XML Id of the plugin, but passes it as the `pluginId` parameter, which should be the numeric id.

I believe the correct parameter should be `xmlId`.

I verified it with curl and it was indeed the case:

Before:
```
curl -i --header "Authorization: Bearer perm:..." -F pluginId=zio.intellij.zio-intellij -F file=@./target/zio-intellij-2020.2.1.2.zip https://plugins.jetbrains.com/plugin/uploadPlugin
HTTP/2 400
...
For input string: "zio.intellij.zio-intellij"%
```

With numeric Id:
```
curl -i --header "Authorization: Bearer perm:..." -F pluginId=13820 -F file=@./target/zio-intellij-2020.2.1.2.zip https://plugins.jetbrains.com/plugin/uploadPlugin
HTTP/2 201
...
The ZIO for IntelliJ plugin has been successfully uploaded% 
```

With `xmlId`:
```
curl -i --header "Authorization: Bearer perm:..." -F xmlId=zio.intellij.zio-intellij -F file=@./target/zio-intellij-2020.2.1.2.zip https://plugins.jetbrains.com/plugin/uploadPlugin
HTTP/2 201
...
The ZIO for IntelliJ plugin has been successfully uploaded% 
```

### PR DESCRIPTION
**Pull request by hmemcpy**
Fixes #78

### CODE REVIEW

**Comment by hmemcpy** [comment]
Thanks very much for accepting the PR! Any chance this version will be released soon?

**Comment by mutcianm** [comment]
released in 3.7.6

**Comment by hmemcpy** [comment]
Thanks a lot!!

**Comment by mutcianm** [comment]
Correct build published as 3.7.7

**Pull request merged**
